### ISSUE TITLE
Add the new diagram layout data structure

### ISSUE THREAD

**Issue by gcoutable** [eclipse-sirius/sirius-web#1527]
Remove:
- Position#UNDEFINED
- Node#position
- Node#size
- Edge#routingPoints
- Edge#sourceAnchorRelativePosition
- Edge#targetAnchorRelativePosition
- Label#position
- Label#size
- Label#alignment
- NodeDescription#childrenLayoutStrategyProvider should be childrenLayoutStrategy (should not be dynamic)
- Node#childrenLayoutStrategy (can be computed from description)

Add:

```
public record DiagramLayoutData (
  Map<String, NodeLayoutData> nodeLayoutData,
  Map<String, EdgeLayoutData> edgeLayoutData
  Map<String, LabelLayoutData> labelLayoutData
) {}

public record NodeLayoutData (
  Position position,
  Size size,
) {}

public record EdgeLayoutData (
  Ratio sourceAnchorRelativePosition,
  Ratio targetAnchorRelativePosition,
  List<Position> routingPoints
) {}

public record LabelLayoutData (
  Position position,
  Size size,
  Position alignment
) {}
```

**Comment by sbegaudeau** [comment]
This does not imply any change on the frontend side since we could introduce things like this:

```
public class NodeSizeDataFetcher {
  public Size get(DataFetcherEnvironment environment) {
    var diagramData = environment.getLocalContext().get("diagramData");
    var nodeId = ((Node) environment.getSource).getId();
    return diagramData.getLayoutData()nodeLayoutData.get(nodeId).size;
  }
}
```

As a result, we could probably move `Size` and `Position` from `sirius-components-diagrams` to `sirius-components-layout-api` and remove all the related code from the various components. This would give us a good opportunity to get rid of `Position#UNDEFINED` and `Size#UNDEFINED`
