### ISSUE TITLE
Add an example showing how to contribute to the details view with the view DSL

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-web#1916]
We need to show how to use a form from a view DSL in order to contribute to the properties view.

We could convert the content of the class `org.eclipse.sirius.components.view.emf.diagram.NodeStylePropertiesConfigurer` to multiple form description using the view DSL and load them, convert them to programmatic FormDescription and finally register them in the configurer.

**Comment by pcdavid** [comment]
The original idea was to to rewrite the `NodeStylePropertiesConfigurer` but it is a relatively complex use case which exposes some limitations and bugs in the current View-based Form support (for example, it is not possible to provide a completion provider for a text field defined with the View DSL). This would result in a functional regression if we replaced the existing `NodeStylePropertiesConfigurer` with a more limited version.

Instead, we chose to provide a slightly customized _Details_ view for the Attribute elements in the Domain DSL.

Before, with the default/generic rules applied:

![screenshot-2023-05-24_16-45](https://github.com/eclipse-sirius/sirius-components/assets/10608/676dec56-975d-488c-92c5-a42b221dc21f)

After, with the Form defined in the new `org.eclipse.sirius.web.sample.configuration.DomainPropertiesConfigurer`:

![screenshot-2023-05-25_11-01](https://github.com/eclipse-sirius/sirius-components/assets/10608/1f804392-ab22-4929-85ad-6217f285a50c)

Differences:
- the page's title shows the attribute's type
- the type is displayed before the cardinality
- the type is selected using a Select/Combo instead of a radio group
- the type names are "Capitalized" intsead of "FULL_UPPER_CASE"
- an additional read-only label shows the cardinality corresponding to the optional/many flag combination.
