### ISSUE TITLE
Widgets from different groups share the same ID

### ISSUE THREAD

**Issue by frouene** [eclipse-sirius/sirius-web#1991]
The representation ID of all widgets is calculated using a counter defined for each group. In a form with multiple groups, the widgets in each group will share the same id.

In this example : 

![image](https://github.com/eclipse-sirius/sirius-components/assets/128395825/209dadfb-5ba1-48b3-b1cd-7af2aa9e4669)

The _BUTTON 1_ and _BUTTON 2_ have `id = sirius:///ae4ea49a-ecc1-4144-af1d-6a2d4388dabe#/#0`.

In the backend, to get the behavior of the widget, we use this identifier to retrieve from all the widgets the one that has been triggered. It will always be the one of the first group that will match, so in our example, by triggering the _BUTTON 2_ it will be the _BUTTON 1_ behaviour used.

**Comment by pcdavid** [comment]
Steps to reproduce:

1. Create a new studio and upload the View model in this zip: [ViewNewModel.zip](https://github.com/eclipse-sirius/sirius-components/files/11561872/ViewNewModel.zip). It defines a Form on `flow::System` with two groups, each with one button. The button in the first group increases the weight of the `System` instance, the button in the second group increases its temperature.
![screenshot-2023-05-25_08-49](https://github.com/eclipse-sirius/sirius-components/assets/10608/93407b18-40ed-4223-9b32-f2b762d40717)

2. Create a new "Flow" project, and create an instance of the Form above on the top-level System.
3. Make sure the System is selected in the explorer so that its details are visible.
4. Click on the first button: the System's weight increases (OK)
5. Click on the second button: the System's **temperatrure** should increase, but instead it's the weight (**KO**). Clicking on the second button actually invokes the behavior of the first one (more precisely: clicking on the _N_th button on *any* group invokes the _N_th button of the *first* group

https://github.com/eclipse-sirius/sirius-components/assets/10608/a2d2e6ba-7745-4f1d-a2fc-14bcc8375a30

**Comment by gcoutable** [comment]
The new [ViewNewModel.zip](https://github.com/eclipse-sirius/sirius-web/files/12739071/ViewNewModel.zip) version for 2023.10.0
