### ISSUE TITLE
Tool reconnection doesn't work anymore for applications with a custom IViewRepresentationDescriptionSearchService

### ISSUE THREAD

**Issue by frouene** [eclipse-sirius/sirius-web#2003]
### Screenshots

![reconnect](https://github.com/eclipse-sirius/sirius-components/assets/128395825/630a320f-272e-4d31-8b10-ca766dae2c85)

### Actual behavior

The reconnection tool return an _ErrorPayload_ with an empty message.

**Comment by pcdavid** [comment]
Actually, tool reconnection works fine in Sirius Web's sample application.

My understanding is that Sirius **Components** hard-codes in `ViewReconnectionToolsExecutor.execute()` the logic to locate the `EdgeDescription`. This hard-coded logic happens to work in the context of Sirius **Web**, but for other applications which manage their View instances differently, we should delegate to `IViewRepresentationDescriptionSearchService.findViewEdgeDescriptionById(String)` so that their own implementation of `IViewRepresentationDescriptionSearchService`, consistent with their View models integration, is used instead.
