### ISSUE TITLE
Layout objects do not appear in the explorer anymore

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-web#2026]

**Comment by gcoutable** [comment]
This issue has occurred since #1975 when we started to rely on emf edit to get the content of an object (which is nice by the way).
But as far as I know, the `childrenLayoutStrategy` feature has never been a "children feature" of `NodeDescription`.
Maybe it should.

![image](https://github.com/eclipse-sirius/sirius-components/assets/7371042/50343539-55ac-40ab-be80-8d98e5962aa9)

![image](https://github.com/eclipse-sirius/sirius-components/assets/7371042/7012a28d-b649-4c2e-85db-958a18e939ea)
