### ISSUE TITLE
Feature request: plugin support?

### ISSUE THREAD

**Issue by mt-empty** [eclipse-sirius/sirius-web#24]
I'm planning to use [Acceleo](https://marketplace.eclipse.org/content/acceleo) to generate code of my model. 
Acceleo is a plugin for Sirius desktop, I'd like to be able to use it to generate code within Sirius-web (without having to open Sirius desktop).

Is this something that you could support in the future?

**Comment by pcdavid** [comment]
Hi,

This kind of thing is already possible using the existing mechanisms.

A concrete Sirius Web application is built on Spring Boot, which has its own extensibility mechanisms built-in.

To add something like Acceleo support you would need to:
* implement the actual generation service in a new module for the backend, see for example all the existing ones at https://github.com/eclipse-sirius/sirius-components/tree/master/backend. Acceleo is available as Maven artifacts on https://repo.eclipse.org.
* add an API entry point (either REST or GraqhQL) to your backend so that the frontend can call this new service. If you chose a REST endpoint, you can use the normal Spring Boot APIs to register a new controller. If you chose GraphQL, see `org.eclipse.sirius.web.graphql.utils.schema.ITypeCustomizer` and `org.eclipse.sirius.web.graphql.utils.schema.ITypeProvider` for how to extend the Sirius Web GraphQL Schema with your own types and additional fields.
* modify the frontend code to add the required UI elements to trigger the backend service. At the moment the only way to do this is to fork the `sirius-components/frontend` code.
