### ISSUE TITLE
Make handle appear only conditionally

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-web#2443]
By conditionally, I mean something like on selection or on hover, I don't know, it will have to be defined

**Comment by mbats** [comment]
Handles should be visible only when element is selected.
Handles should be visible only when there is an edge with the node as source/target or reconnect tool defined.

**Comment by pcdavid** [comment]
This actually covers several related but distinct changes.
To make them explicit and be sure we don't forget any:

- [ ] distinguish between the "create connection" handles displayed on the nodes 4 faces to _start the edge creation process_ from the "edge source/target handle" displayed on an existing edge's extremity to trigger a reconnection;
- [ ] only display the "create connection" handles (resp. "edge source/target handle") on a node (resp. edge) when it is selected;
- [ ] the "create connection" handles should appear "greyed out" when their parent node is selected, but highlighted when hovered (to indicate they are active elements);
- [ ] while in the process of dragging a "create connection" handle (so during the edge reconnection process), highlight the compatible nodes and fade the incompatible ones. This should be consistent with the feedback we have for the graphical DnD.
- [ ] for both edge creation and reconnection, allow the user to point anywhere inside the target node, not only on a tiny target/handle;
- [ ] distribute the endpoints of multiple edges which share the same side of a node so that they are visually distinguished. This includes the case where a single edge "to self" has both its endpoints on the same face of the same node.

If it ends up being too complex to handle all of this in this issue/PR we'll open a new one to finish the work, but all of these *must* be handled in 2023.12.0

**Comment by mcharfadi** [comment]
Fixed with https://github.com/eclipse-sirius/sirius-web/issues/2572
