### ISSUE TITLE
The create element on a widget ref for a mono valued and containment reference isn't working if there is already a value.

### ISSUE THREAD

**Issue by frouene** [eclipse-sirius/sirius-web#2456]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [ ] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- latest

### Steps to reproduce

An example model with a mono valued and containment reference: 

[Studio.zip](https://github.com/eclipse-sirius/sirius-web/files/12846296/Studio.zip)

With a widget reference on this reference, if there is already a value setted, then the create new element action is not working.

### Actual behavior

Nothing append and there is a snackbar with a generic error.

**Comment by adaussy** [comment]
In fact this problem is bigger than the case of mono valued containement reference widget.

It appears each time the IEditService tries to create a new instance in a mono containment reference feature that already contains a value. It can be reached either using the + icon on the widget reference or when using the _Create new element_ menu in the _Explorer_ view.

There is two solution to that problème.

1. Delete the previous value before adding the new one.

Something like this in _org.eclipse.sirius.components.emf.services.EditService.createObject(AdapterFactoryEditingDomain, EObject, CommandParameter)_

```java
  private Optional<Object> createObject(AdapterFactoryEditingDomain editingDomain, EObject eObject, CommandParameter commandParameter) {
        Optional<Object> objectOptional = Optional.empty();

        // NEW CODE START
        if (commandParameter.getEStructuralFeature() instanceof EReference ref && ref.isContainment() && !ref.isMany() && eObject.eGet(ref) != null) {
           delete(eObject.eGet(ref));
        }
        // NEW CODE HERE

        Command createChildCommand = CreateChildCommand.create(editingDomain, eObject, commandParameter, Collections.singletonList(eObject));
        editingDomain.getCommandStack().execute(createChildCommand);
        Collection<?> result = createChildCommand.getResult();
        if (result.size() == 1) {
            Object child = result.iterator().next();
            if (child instanceof EObject && EcoreUtil.isAncestor(eObject, (EObject) child)) {
                objectOptional = Optional.of(child);
            }
        }
        return objectOptional;
    }
```

This solution can be a bit hard on the delete element and its subtree

2. Send a message to the fronted to notify that the element can not be created because the feature is fulle

Something like this in _org.eclipse.sirius.components.emf.services.EditService.createObject(AdapterFactoryEditingDomain, EObject, CommandParameter)_

```java
  private Optional<Object> createObject(AdapterFactoryEditingDomain editingDomain, EObject eObject, CommandParameter commandParameter) {
        Optional<Object> objectOptional = Optional.empty();

        // NEW CODE START
        if (commandParameter.getEStructuralFeature() instanceof EReference ref && ref.isContainment() && !ref.isMany() && eObject.eGet(ref) != null) {
            this.feedbackMessageService
                    .addFeedbackMessage(new Message("Unable to create a new instance of " + commandParameter.getEValue().eClass().getName() + " in " + this.objectService.getLabel(eObject)
                            + " in feature " + commandParameter.getEStructuralFeature().getName() + " because it has reach its upper bound cardinality.", MessageLevel.WARNING));
            return Optional.empty();
        }
        // NEW CODE END

        Command createChildCommand = CreateChildCommand.create(editingDomain, eObject, commandParameter, Collections.singletonList(eObject));
        editingDomain.getCommandStack().execute(createChildCommand);
        Collection<?> result = createChildCommand.getResult();
        if (result.size() == 1) {
            Object child = result.iterator().next();
            if (child instanceof EObject && EcoreUtil.isAncestor(eObject, (EObject) child)) {
                objectOptional = Optional.of(child);
            }
        }
        return objectOptional;
    }
```
This solution need more rfactoring to forward the message to the front end
