### ISSUE TITLE
Build the backend components.

### ISSUE THREAD

**Issue by IvanGuerrero** [eclipse-sirius/sirius-web#2758]
* [ X] **I have checked that this bug has not yet been reported by someone else**

Dear all,

I try to execute the project following the steps in "Building".
But when I want execute the backend components it presents an error.
In attacchment the error and the logs

### Screenshots

[SIRIUS WEB ERROR.zip](https://github.com/eclipse-sirius/sirius-web/files/13588766/SIRIUS.WEB.ERROR.zip)
[SIRIUS WEB ERROR.zip](https://github.com/eclipse-sirius/sirius-web/files/13588771/SIRIUS.WEB.ERROR.zip)

### Steps to reproduce
mvn clean install -f packages/pom.xml

**Comment by HopedWall** [comment]
Having the same problem, does anybody know how to fix it? There appears to be a problem when running the tests for `sirius-web-persistence`. The stack trace is attached. Running macOS Sonoma 14.1.2.

[logs.txt](https://github.com/eclipse-sirius/sirius-web/files/13601715/logs.txt)

**Comment by pcdavid** [comment]
This is usually the symptom when you do not have Docker installed and running.
The integration tests of the `sirius-web-persistence` module need a running Docker to launch a containerized PostgreSQL database.

Check https://docs.docker.com/engine/install/ for installation instructions for your OS.

You can also pass `-DskipTests` to the Maven invocation so that the tests are ignored if you do not want (or can not) install Docker.

**Comment by HopedWall** [comment]
It's working now (for me at least), thank you!

May I suggest adding this requirement to the readme? Perhaps I just missed it, but I think it could be helpful.

**Comment by IvanGuerrero** [comment]
Many thanks.
