### ISSUE TITLE
npm ci produces 401 Unauthorized error

### ISSUE THREAD

**Issue by kolovos** [eclipse-sirius/sirius-web#3144]
I am trying to follow the instructions for [building the frontend and backend components of Sirius Web](https://github.com/eclipse-sirius/sirius-web?tab=readme-ov-file#build-the-frontend--backend-components-and-sirius-web). When I run `npm ci` I get the following error and the build fails.

```
npm ERR! 401 Unauthorized - GET https://npm.pkg.github.com/download/@ObeoNetwork/react-trello/2.4.11/384ada405b80fc7105583b43f6aef05e1f26bf3b - authentication token not provided
```

I am on MacOS and my node, npm etc. versions are all within the ranges specified in the instructions.

**Comment by AxelRICHARD** [comment]
Hello,
Since 2024.1.0, we depend on this node package (@ObeoNetwork/react-trello) that comes from github node artifacts repository.
So you should probably add a `$HOME/.npmrc` file with the following content:
`//npm.pkg.github.com/:_authToken=$YOUR_GITHUB_ACCESS_TOKEN`
Indeed, as for the backend part (maven), we need a github token to read modules from github node artifact repository.
I will update the build instructions, thank you.
Regards,
