### ISSUE TITLE
How to customize the metamodel?

### ISSUE THREAD

**Issue by Gelio** [eclipse-sirius/sirius-web#36]
Hey 🙂 I'm excited to see this project, as I have been looking for a way to create a web-based diagram editor.

I wanted to use it, but I have trouble figuring out how I could customize the metamodel. I know I would have to create the `ecore` and `genmodel` files using Obeo Designer, but what then? How do I tell sirius-web to use the new model?

So far in the source code I have only found a path to an `odesign` file (https://github.com/eclipse-sirius/sirius-web/blob/4ce40bc68e50d1a0704804b189ab6f3b134612a7/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration/SampleSiriusConfiguration.java#L30) and the `SampleEMFConfiguration` (https://github.com/eclipse-sirius/sirius-web/blob/4ce40bc68e50d1a0704804b189ab6f3b134612a7/backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration/SampleEMFConfiguration.java) that (if I'm not mistaken) instructs sirius-component's backend to use that generated code.

Could you help me out with a list of steps describing how I could go about changing the metamodel used by sirius-web?

**Comment by pcdavid** [comment]
Hi,

Currently the only way to add support for a new business domain is to define it using a "classical" EMF-based metamodel, generated from the Eclipse-based EMF tooling. Once you have it, you need to register the corresponding EMF `EPackage` and `AdapterFactory`, as you correctly guessed.

Then to create an actual modeler to edit instances of this domain you could define your own diagram definition in plain Java, but the current APIs we offer are rather low-level so this is the "hard core mode". The easiest way for now is to use Sirius Desktop to create the modeler definition. It will produce a `.odesign` file which, in most simple cases, is a self-contained definition of your diagram. This is the file you then need to reference in the configuration above.

In short, for the time being to create your own modeler on your own custom domain the easiest way it to get a working version on Sirius Desktop (using the tooling available in Obeo Designer CE for example) and then to plug that in Sirius Web. https://github.com/ObeoNetwork/Flow-Designer/, which we use in the sample Sirius Web application is a good example of that. It existed before, was made with/for Sirius Desktop, but with minimal adaptations it can be used inside Sirius Web.

If you are completely new to the Eclipse/EMF world, we have tutorials [here](https://wiki.eclipse.org/Sirius/Tutorials) which start from scratch with [the definition of the domain model](https://wiki.eclipse.org/Sirius/Tutorials/DomainModelTutorial) up to the build and distribution of a Sirius Desktop-based modeler (which you can then use in Sirius Web like the sample application uses the Flow modeler).

We hope to streamline all of these steps in the near future, the end goal being to be able to create and use your own modeler from scratch without leaving your browser, so stay tuned!

**Comment by Gelio** [comment]
Thank you very much for the description, I appreciate it 🙂 I'll experiment with the resources you provided

I'll keep the issue open in case more questions pop up, if that's not a problem

By the way, do you think it would be useful to update the README with some information on how to change the metamodel (i.e. the description you provided)? I could try to submit a PR that adds it

**Comment by sbegaudeau** [comment]
I'll close this issue since an answer has been provided. If you have another question, feel free to reopen it or open a new issue.

**Comment by pcdavid** [comment]
Hi.

The projects in Flow-Designer are not plain/classical Java projects, but Eclipse Plug-in Projects. 

Tycho and Obeo Designer know about this kind of projects and know where to look for their dependencies and how to resolve them to build a build-path/classpath: the dependencies are declared in the OSGi `META-INF/MANIFEST.MF`, and will be resolved from the Target Platform definition which refers to p2 repositories where to find the OSGi bundles (JARs) required.

VS Code, NeoVim or any other IDE which is not aware of this type of project will not find the dependencies. If it knows about Maven it will look inside the `pom.xml` files, but the dependencies are not declared there.

I don't think any non Eclipse-based IDE knows how to deal with the specifics of Eclipse Plug-in Projects (VS Code uses `eclipse.jdt.ls` which indeed comes from Eclipse, but is a lower-level component and does not know about these).

[Spring Tool Suite for Eclipse](https://spring.io/tools) is based on Eclipse, and provided you install the Eclipse PDE (Plug-in Developement Environment, not sure if it's installed by default) you can have a single IDE which can deal with both plain Maven projects (through M2E) and Eclipse Plug-ins (through PDE).

Otherwise you'll need to explicitly declare the project dependencies in the `pom.xml`, this needs finding Maven repos where they are available (which is not always easy, as projects from the Eclipse world tend to publish to p2 repos only).

EMF itself is available in Maven Central, and https://repo.eclipse.org/ contains others. In particular the Sirius Desktop JARs that Sirius Web depends on are obtained from there. See https://github.com/eclipse-sirius/sirius-components/blob/master/backend/sirius-web-compatibility/pom.xml#L43 and the dependencies starting at https://github.com/eclipse-sirius/sirius-components/blob/master/backend/sirius-web-compatibility/pom.xml#L143.
