### ISSUE TITLE
Multiple textfields in a form in a for is not working

### ISSUE THREAD

**Issue by mcharfadi** [eclipse-sirius/sirius-web#3720]
When editing the value of a textfield inside a for, the representation can become unresponsive
Here I'm not able to further edit the first edited value
![ForTextIssue](https://github.com/eclipse-sirius/sirius-web/assets/121878084/d7e7d00a-4f05-4c95-a9d3-ccc5360b4273)

https://github.com/eclipse-sirius/sirius-web/assets/121878084/4c29495e-f5d6-414d-949d-e92c8119f43d

**Comment by sbegaudeau** [comment]
This is on purpose, we cannot distinguish widgets that:

- are defined on the same semantic element
- with the same definition
- with the same label

And the end user cannot either. See ADR 108 for more details.

The only way we could really distinguish them would be by asking the specifier for an identifier for each widget instance (some sort of identifierExpression). It's the same in diagrams where you cannot have two nodes with the same:

- node description
- semantic element
- parent node
- containment kind (they are both a child or border node of their parent)

We can't distinguish them otherwise. Sirius desktop and web have never asked the specifier to provide such identification. It would be helpful for some tricky use cases but cumbersome for most use cases. It's also the same issue with multiple edges of the same kind between two nodes.
