### ISSUE TITLE
Store form and property payload in a context

### ISSUE THREAD

**Issue by mcharfadi** [eclipse-sirius/sirius-web#3758]

**Comment by sbegaudeau** [comment]
I'm reopening this issue since the fix does not match what I'm expecting:

- There's no need to have two parallel way to store some stateful data in FormRepresentation.
- All form based representations on the frontend should be impacted in a similar manner (Related elements, diagram filter, etc)
- It does not make sense for the hook `useDetailsViewSubscription` to both return the form and the payload since the form is derived from the payload just like it does not make sense to store both the payload and the form in FormRepresentation.
