### ISSUE TITLE
The variables input contains a field name 'projectId' that is not defined for input object type 'CreateDocumentInput' 

### ISSUE THREAD

**Issue by mt-empty** [eclipse-sirius/sirius-web#45]
With the latest build, I have been getting the following error whenever I try to select a model (`Create a new Model` `Select the model to create`). 
```
2021-03-15 22:27:20.903  WARN 317728 --- [nio-8080-exec-5] o.e.s.w.s.g.c.GraphQLController          : {
  "errors" : [ {
    "message" : "The variables input contains a field name 'projectId' that is not defined for input object type 'CreateDocumentInput' ",
    "extensions" : {
      "classification" : "ValidationError"
    }
  } ]
}
```
I haven't modified anything in the source code.
I was not getting this error in cae4eaa9a0299e28895293d41467057ca2fe78d4

A workaround is to click on the three dots next to the project name and click on `new model`.

**Comment by pcdavid** [comment]
This should have been fixed in sirius-components by https://github.com/eclipse-sirius/sirius-components/commit/ff3ffed7a597934c045fec85aa806d4155157e99, but the sirius-web sample application has not been updated yet to consume a version with the fix.

In the mean time you can create new models from the project context menu in the header. The dialog used in this part of the UI does not have the issue.
