### ISSUE TITLE
npm run build (failed)

### ISSUE THREAD

**Issue by microwan** [eclipse-sirius/sirius-web#5]
Hello ,

I have tried to launch npm run build

i have this issue
![2020-10-22 15_18_57-MINGW64__c_Project_sirius_sirius-web_frontend](https://user-images.githubusercontent.com/2742075/96877581-225cba00-147a-11eb-95f7-70caafe90297.png)

Do you have an idea ?

  Best regards

               Erwan

**Comment by rkvsraman** [comment]
You need to generate an github access token .... details here https://stackoverflow.com/questions/58919401/installing-packages-from-github-npm-registry-auth-error-401 


and then create a .npmrc file in frontend dir of sirius-web with following content
```
registry=https://npm.pkg.github.com/eclipse-sirius
//npm.pkg.github.com/:_authToken=<Token>
```

You also have to remove mention of  **"@obeo/sirius-components": "0.1.27",** from package.json and couple of other files like  
 **frontend/src/index.js 
 frontend/src/main/Main.js** 


This worked for me.

**Comment by pcdavid** [comment]
The error message about a missing `react-scripts` seem to indicate that you did not run `npm install` before `npm run build` (so `react-scripts` is not installed in `node_modules`) or that it failed half-way, maybe because of the token issue mentioned by @rkvsraman.

I have completed the README with (hopefully) all the feedback we've had for now, hopefully they are complete now.

Closing this, but do not hesitate to reopen if you still have the issue with the current instructions.
