### ISSUE TITLE
The moving element may not be the selected one

### ISSUE THREAD

**Issue by gcoutable** [eclipse-sirius/sirius-web#552]
### Screenshots

https://user-images.githubusercontent.com/7371042/122062414-adb30300-cdef-11eb-9989-b418d2dd4ef8.mp4

### Steps to reproduce

In manual layout:

1. Move an element to make incremental layout does some adjustment.
2. While elements are still moving, select another element and try to move it.
3. If you were fast enough, the moving element is the previously selected element, not the current one.

### Expected behavior

The current selection should move.

### Actual behavior

The previously selected element is moving instead of the currently selected element.

**Comment by AxelRICHARD** [comment]
When an element (a not selected one) is moved, no selection event is raised. May be the problem comes from here.
Another consequence of that is the Properties view is not updated, even though the moved element seems selected on screen.

**Comment by AxelRICHARD** [comment]
When an element is moved, the `handleMoveAction` in `WebSocketDiagramServer.tsx` is only called after a mouseUp event.


method | -- | file
-- | -- | --
handleMoveAction | @ | WebSocketDiagramServer.tsx:215
handle | @ | WebSocketDiagramServer.tsx:140
ActionDispatcher.handleAction | @ | action-dispatcher.ts:132
anonymous) | @ | action-dispatcher.ts:76
Promise.then (async) |   |  
ActionDispatcher.dispatch | @ | action-dispatcher.ts:72
actionDispatcher.dispatch | @ | DependencyInjection.ts:289
MouseTool.handleEvent | @ | mouse-tool.ts:72
MouseTool.mouseUp | @ | mouse-tool.ts:115
...

When the previously selected element is moving instead of the currently selected element, the element id in `handleMoveAction` is the one of the previously selected element.

The problem must comes from sprotty itself.

**Comment by pcdavid** [comment]
This concerned the old Sprotty-based diagram frontend. Obsolete.
